import numpy as np
myList = [1, 2, 3]
print(f"type of arr: {type(myList)}")
print(myList)
myArray = np.array(myList)
print(f"type of arr: {type(myArray)}")
print(myArray)
tenSizeArr = np.arange(0, 10, 2)
print(tenSizeArr)
fiveByFiveArrZeros = np.zeros(shape=(3, 3))
print(type(0.))
print(fiveByFiveArrZeros)
#                       height, width
fiveByFiveArrOnes = np.ones((3, 3))
print(fiveByFiveArrOnes)
np.random.seed(101)
genArr1 = np.random.randint(0, 100, 10)
print(genArr1)
genArr2 = np.random.randint(0, 100, 10)
print(genArr2)
print(f"Max: {genArr1.max()}, Min: {genArr1.min()}")
print(f"Max: {genArr1.argmax()}, Min: {genArr1.argmin()}")
print(f"Mean: {genArr1.mean()}")
print(f"Shape: {genArr1.shape}")
print(f"Shape: {genArr1.reshape(2, 5)}")
matrix_1 = np.arange(0, 100).reshape(10, 10)
print(f"Matrix: {matrix_1}")
print(f"Matrix: {matrix_1[1, 4]}")
print(f"Matrix: {matrix_1[4, 6]}")
print(f"Matrix Column: {matrix_1[:, 4]}")
print(f"Matrix Row: {matrix_1[4, :]}")
print(f"Matrix P: {matrix_1[0: 3, 0: 3]}")
print(f"Matrix P: {matrix_1[5: 8, 0: 3]}")
matrix_1[5: 8, 0: 3] = 5
print(f"Matrix changed: {matrix_1}")
newMatrix = matrix_1.copy()
newMatrix[0:6,:] = 55
print(f"New Matrix: {newMatrix}")